import { PosterSearchData } from "./types/interface";

export const template: PosterSearchData[] = [
  {
    title: "Mugyutto! Black Clover",
    OverallScore: 6.41,
    photoPath: "https://cdn.myanimelist.net/images/anime/1066/101736.jpg",
    type: "ONA",
    malId: 40031,
    api: true,
  },
  {
    title: "Black Clover: Jump Festa 2018 Special",
    OverallScore: 6.29,
    photoPath: "https://cdn.myanimelist.net/images/anime/1585/96894.jpg",
    type: "Special",
    malId: 38768,
    api: true,
  },
  {
    title: "Black Clover",
    OverallScore: 8.07,
    photoPath: "https://cdn.myanimelist.net/images/anime/2/88336.jpg",
    type: "TV",
    malId: 34572,
    api: true,
  },
  {
    title: "Black Clover Movie",
    OverallScore: 0,
    photoPath: "https://cdn.myanimelist.net/images/anime/1833/113800.jpg",
    type: "Movie",
    malId: 48585,
    api: true,
  },
  {
    title: "Hachimitsu to Clover",
    OverallScore: 8.03,
    photoPath: "https://cdn.myanimelist.net/images/anime/11/73923.jpg",
    type: "TV",
    malId: 16,
    api: true,
  },
  {
    title: "Black Clover: Jump Festa 2016 Special",
    OverallScore: 6.75,
    photoPath: "https://cdn.myanimelist.net/images/anime/7/84639.jpg",
    type: "OVA",
    malId: 33950,
    api: true,
  },
  {
    title: "Hachimitsu to Clover II",
    OverallScore: 8.23,
    photoPath: "https://cdn.myanimelist.net/images/anime/6/11040.jpg",
    type: "TV",
    malId: 1142,
    api: true,
  },
  {
    title: "Black Cat (TV)",
    OverallScore: 7.35,
    photoPath: "https://cdn.myanimelist.net/images/anime/1485/110010.jpg",
    type: "TV",
    malId: 68,
    api: true,
  },
  {
    title: "Darker than Black: Kuro no Keiyakusha",
    OverallScore: 8.09,
    photoPath: "https://cdn.myanimelist.net/images/anime/5/19570.jpg",
    type: "TV",
    malId: 2025,
    api: true,
  },
  {
    title: "Kuroshitsuji",
    OverallScore: 7.7,
    photoPath: "https://cdn.myanimelist.net/images/anime/5/27013.jpg",
    type: "TV",
    malId: 4898,
    api: true,
  },
  {
    title: "Black Fox",
    OverallScore: 6.74,
    photoPath: "https://cdn.myanimelist.net/images/anime/1904/119291.jpg",
    type: "Movie",
    malId: 37498,
    api: true,
  },
  {
    title: "Black Jack (TV)",
    OverallScore: 7.6,
    photoPath: "https://cdn.myanimelist.net/images/anime/11/14889.jpg",
    type: "TV",
    malId: 2213,
    api: true,
  },
  {
    title: "Kuroshitsuji II",
    OverallScore: 7.18,
    photoPath: "https://cdn.myanimelist.net/images/anime/4/50499.jpg",
    type: "TV",
    malId: 6707,
    api: true,
  },
  {
    title: "Black Lagoon: Roberta's Blood Trail",
    OverallScore: 8.03,
    photoPath: "https://cdn.myanimelist.net/images/anime/8/75529.jpg",
    type: "OVA",
    malId: 4901,
    api: true,
  },
  {
    title: "Black Cat (TV): Toozakaru Neko",
    OverallScore: 7.11,
    photoPath: "https://cdn.myanimelist.net/images/anime/5/22527.jpg",
    type: "Special",
    malId: 2589,
    api: true,
  },
  {
    title: "Bleach Movie 3: Fade to Black - Kimi no Na wo Yobu",
    OverallScore: 7.5,
    photoPath: "https://cdn.myanimelist.net/images/anime/3/64689.jpg",
    type: "Movie",
    malId: 4835,
    api: true,
  },
];
